### ISSUE TITLE
API Key and Token - How to obtain

### ISSUE THREAD

**Issue by buff0k** [elig0n/ewelink-tray#1]
Hi, first off, thanks for trying to achieve something useful with the coolkit API, however I have some questions regarding how to obtain a API key and Token as required for the .ini file? 
I am looking at creating a skill for the Mycroft.ai to support eWeLink integration and can't get any information from coolkit.cc so I was hoping to build on some of your code if I can first get it to work on my computer.

**Comment by elig0n** [comment]
Hi, you'll have to sniff it, you can use an http proxy like Charles.  You can see more info here https://github.com/gbro115/homebridge-ewelink

**Comment by buff0k** [comment]
I assumed as much, did that, works fine until the API expires (Logging in again). I have requested API access from coolkit.cc but they don't seem inclined to assist.
Thanks for the work.
